#!/usr/bin/env bash
# Transfers a file from the client to the server.

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

ssh -i "$4" -o StrictHostKeyChecking=no "$3@$2" "mkdir -p ~/"
scp -i "$4" "$1" "$3@$2:~/"
