#!/usr/bin/env bash
# Installs Nginx on the web server.

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

cat << EOF > /etc/nginx/sites-available/default
server {
	listen 80;
	server_name localhost;

	location / {
		root /var/www/html;
		index index.html;
	}
}
EOF

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart

curl localhost
