#!/usr/bin/env bash
# Installing Nginx web server.

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i "s/listen 80 default_server;/listen 80;/g" /etc/nginx/sites-available/default

sudo service nginx restart

sudo curl localhost
