#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to another page with a 301 Moved Permanently response.

sudo apt-get update
sudo apt-get -y nginx

sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www

mkdir -p /var/www/html/
echo "Hello World!" > /var/www/html/index.html

echo "server {
    listen 80 default_server;
    server_name _;

    location /redirect_me {
        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx start
