#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header.

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/sites-available/default

sudo service nginx restart

echo 'Nginx configured with custom HTTP response header (X-Served-By)'
