#!/usr/bin/env bash
# This script displays information about users from /etc/passwd.

while IFS=":" read -r username userid info groupid password home_directory shell; do
	echo "The user $username is part of the $groupid gang, lives in $home_directory and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $info"
done < "/etc/passwd"
