#!/usr/bin/env bash
# This script displays numbers with superstitions

count=1
while [ $count -le 20 ]; do
	case $count in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo $count
			;;
		esac
		count=$((count + 1))
done
