#!/usr/bin/env bash
# This script lists directory contents with names after the first dash.

for file in *; do
	if [[ ! $file =~ ^\..* && ( -f "$file" || -d "$file" ) ]]; then
		name_after_dash=$(echo "$file" | cut -d'-' -f2-)
		echo "$name_after_dash"
	fi
done
